version: "3.2"
services:
  # todo indent w/ 4 spaces for readability. yaml doesn't allow tabs
  wordcamp.test:
    build:
      context: .docker
      dockerfile: Dockerfile
    volumes:
      - "./public_html/wp-content:/usr/src/public_html/wp-content"
      - ".docker/wp-config.php:/usr/src/public_html/wp-config.php"
      # todo should mount nginx.conf, php-form.conf, install-plugin-theme.sh, etc too? then could edit and re-run rather than having to copy and rebuild
      # todo mount host ~/dotfiles into container /root, but can't b/c outside .docker folder?
    ports:
      - "80:80"
      - "443:443"
      - "1080:1080"
    command: >
      bash -c "
               git -C /usr/src/public_html/mu pull &&
               touch /usr/src/public_html/wp-content/mu-plugins/blocks/build/blocks.min.js &&
               touch /usr/src/public_html/wp-content/mu-plugins/blocks/build/blocks.min.css &&
               nginx &&
               mailcatcher --http-ip 0.0.0.0 &&
               php-fpm"
      # todo maybe setup cron job to run the git pull, like production? the above will only run when starting container
    # todo configure entrypoint to work around annoying wp-cli allow-root problem -- https://github.com/wp-cli/wp-cli/issues/1838#issuecomment-434077907

  wordcamp.db:
    build:
      context: .docker
      dockerfile: mysql.Dockerfile
      # todo rename ^ to Dockerfile.mysql and the other to Dockerfile.webhead or something, for clarity. maybe also rename `wordcamp.db` to something more correct.
    volumes:
      - ".docker/database:/var/lib/mysql"
    ports:
      # todo document that 3307 to avoid conflicts w/ host mysql server?
      - "3307:3306"
