version: "3.2"
services:
    wordcamp.test:
        build:
            context: .docker
            dockerfile: Dockerfile.php-fpm
        volumes:
            - "./public_html:/usr/src/public_html"
            - ".docker/bin:/var/scripts"
            - ".docker/data:/usr/src/data"
            - ".docker/wp-config.php:/usr/src/public_html/wp-config.php"
            - ".docker/wp-cli.yml:/usr/src/public_html/wp-cli.yml"
            - ".docker/config/nginx.conf:/etc/nginx/sites-enabled/default"
            - ".docker/config/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-www.conf"
            - ".docker/config/composer.json:/usr/src/composer.json"
            - ".docker/config/msmtprc:/etc/msmtprc"
            # todo mount host ~/dotfiles into container /root, but can't b/c outside .docker folder?
        ports:
            - "80:80"
            - "443:443"
            - "1080:1080"
        environment:
            - IS_LOCAL_DEV=1
        # todo configure entrypoint to work around annoying wp-cli allow-root problem -- https://github.com/wp-cli/wp-cli/issues/1838#issuecomment-434077907

    # todo document why this is a separate container
    wordcamp.db:
        build:
            context: .docker
            dockerfile: Dockerfile.mysql
            # todo maybe rename `wordcamp.db` to something more correct.
        volumes:
            - ".docker/database:/var/lib/mysql"
            - ".docker/bin:/var/scripts"
        ports:
            # todo document that 3307 to avoid conflicts w/ host mysql server?
            - "3307:3306"
